# 特定のコミットに対する各CIの実行結果をチェックしすべて成功or実行されていない(=neutral)の状態であれば成功とみなします
#
# 用途としてはフォルダごとにCIが独立している場合にGitHub上でそれぞれのチェックを強制にすると
# 対象のファイルを変更しない場合にチェックが行われずマージができなくなります。
# そこで、このアクションを通じて全てのCIが完了して成功または実行されていない(=neutral)であることをチェックします。
# これにより、このアクションを必須とすることで結果的に必要なCIが全てパスすることを担保できます。

#
# [動作について]
# この CI は 2 種類のことを行ないます。
# (1) Push をトリガーにして該当の Pull Request(PR) に対して Check Runs を作成
#   ※参考※
#   https://qiita.com/NanimonoDaemon/items/f8addb1befd03b3c0935
#   https://docs.github.com/ja/rest/guides/getting-started-with-the-checks-api
#
# (2) check_run の完了をトリガーにして (1) で作成した Check Runs を更新
#
# (2) で 変更した Check Runs をチェックすることですべてのジョブの完了状態をチェックすることが出来ます
#

name: check-all-ci-result
on:
  check_run:
    types: [completed]

  push:
    # https://stackoverflow.com/questions/57699839/github-actions-how-to-target-all-branches-except-master
    branches:
      - '**'        # matches every branch
      - '!main'     # excludes main

env:
  # Check Runs で作成するジョブの名前
  RESULT_JOB_NAME: statuses-of-all-ci

jobs:
  # Push 時の動作、Check Runs を PR に作成する
  generate-result-job:
    if: github.event_name == 'push'
    runs-on: ubuntu-20.04
    steps:
      - id: generate-queued-result-job
        # https://github.com/LouisBrunner/checks-action/releases/tag/v1.2.0
        uses: LouisBrunner/checks-action@3d24d4813a797720cc4e2080a50bdafb3373aef1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.RESULT_JOB_NAME }}
          status: queued

      # コミットに紐づくすべてのジョブの状態をチェック
      - id: get-all-ci-status
        # https://github.com/lirlia/check-all-ci-completion-action/releases/tag/v1.4.0
        uses: lirlia/check-all-ci-completion-action@78a5fb531d4ed680c93b143132cf0487eec9f9bf
        with:
          commit-hash: ${{ github.sha }}
          disable-errexit: true
          # Push 時に Check Runs で作成したキューイング状態になっているジョブは無視する
          ignore-check-suite-ids: ${{ steps.generate-queued-result-job.outputs.check_id }}
          loop-count: 1
          sleep-seconds: 1

      # 他のジョブが存在しない場合は
      # generate-queued-result-job で作成したジョブを success にする
      - id: update-result-job-to-success
        if: steps.get-all-ci-status.outputs.result == 'success'
        # https://github.com/LouisBrunner/checks-action/releases/tag/v1.2.0
        uses: LouisBrunner/checks-action@3d24d4813a797720cc4e2080a50bdafb3373aef1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check_id: ${{ steps.generate-queued-result-job.outputs.check_id }}
          status: completed
          conclusion: success

  # PR に紐づくジョブが完了したときの動作
  # 他の CI のステータスを見て Check Runs を更新する
  update-result-job:
    #
    # 以下の条件を満たす時に実行される
    # - check_run によって起動される
    # - check_run の所属する check_suite が完了(completed)している
    # - check_run の結果が neutral以外 (neutral: 条件に一致せず実行されない)
    #     see: https://docs.github.com/ja/rest/guides/getting-started-with-the-checks-api
    # - check_run が PR に紐付いている
    #
    if: |
      github.event_name != 'push'
      && github.event.check_run.check_suite.status == 'completed'
      && github.event.check_run.conclusion != 'neutral'
      && toJson(github.event.check_run.pull_requests) != '[]'
    runs-on: ubuntu-20.04
    steps:

      # コミットに紐づく最新の Check Runs の ID を取得
      - id: get-check-suite-id
        # https://github.com/actions/github-script/releases/tag/v6.0.0
        uses: actions/github-script@9ac08808f993958e9de277fe43a64532a609130e
        with:
          script: |
            // for debug
            console.log(context);
            console.log(context.payload.check_run.check_suite);

            const list = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.check_run.head_sha,
              check_name: "${{ env.RESULT_JOB_NAME }}",
              filter: 'latest'
            });

            // for debug
            console.log(list);

            return list.data.check_runs[0].id;
          result-encoding: string

      # コミットに紐づくすべてのジョブの状態をチェック
      - id: get-all-ci-status
        # https://github.com/lirlia/check-all-ci-completion-action/releases/tag/v1.4.0
        uses: lirlia/check-all-ci-completion-action@78a5fb531d4ed680c93b143132cf0487eec9f9bf
        with:
          commit-hash: ${{ github.event.check_run.head_sha }}
          # Push 時に Check Runs で作成したキューイング状態になっているジョブは無視する
          ignore-check-suite-ids: ${{ steps.get-check-suite-id.outputs.result }}
          loop-count: 2
          sleep-seconds: 5

      # すべてのジョブが完了していれば Check Runs で作成したジョブの状態 (conclusion) を
      # get-all-ci-status の結果 (success / fail) で更新する
      - if: steps.get-all-ci-status.outputs.status == 'completed'
        # https://github.com/LouisBrunner/checks-action/releases/tag/v1.2.0
        uses: LouisBrunner/checks-action@3d24d4813a797720cc4e2080a50bdafb3373aef1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check_id: ${{ steps.get-check-suite-id.outputs.result }}
          status: completed
          conclusion: ${{ steps.get-all-ci-status.outputs.result }}
