# svn user を追加/変更する PR を作成します
name: create-and-change-svn-user
on:
  workflow_dispatch:
    inputs:
      slack_member_id:
        description: パスワードを通知したいSlackユーザのメンバーIDを入力してください(slack DMを飛ばすために使用します)
        required: true
      svn_username:
        description: SVNアカウント名を入力してください
        required: true
      svn_groups:
        description: SVNグループ名を入力してください(複数ある場合は , 区切りで入力)
        required: true
        default: "durian-developer"
defaults:
  run:
    shell: bash
jobs:
  create-and-change-svn-user:
    name: Create PR of create or change svn user setting
    runs-on: ubuntu-20.04
    env:
      # 任意の文字列が入りうるフィールドは、Bashで直接使うとインジェクションの危険があるため、ENVに登録して使います
      # https://securitylab.github.com/research/github-actions-untrusted-input/#remediation
      SLACK_MEMBER_ID: ${{ github.event.inputs.slack_member_id }}
      SVN_USERNAME: ${{ github.event.inputs.svn_username }}
      SVN_GROUPS: ${{ github.event.inputs.svn_groups }}
    steps:
      - name: checkout
      # https://github.com/actions/checkout/releases/tag/v2.4.0 相当
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: generate svn user variable
        run: |

          function prefail() { echo "$@" 1>&2; exit 1; }

          # validation check
          [[ "$SLACK_MEMBER_ID" =~ ^[A-Z0-9]+$ ]] || prefail "invalid SLACK_MEMBER_ID: $SLACK_MEMBER_ID"
          [[ "$SVN_USERNAME" =~ ^[A-Za-z\.-]+$ ]] || prefail "invalid SVN_USERNAME: $SVN_USERNAME"
          [[ "$SVN_GROUPS" =~ ^[A-Za-z\.,-]+$ ]] || prefail "invalid SVN_GROUPS: $SVN_GROUPS"

          # generate password
          SVN_PASSWORD=$(./bin/create-svn-user.sh -u $SVN_USERNAME -g $SVN_GROUPS)

          # mask password
          # see: https://docs.github.com/ja/actions/using-workflows/workflow-commands-for-github-actions#example-masking-an-environment-variable
          echo "::add-mask::$SVN_PASSWORD"
          echo "SVN_PASSWORD=$SVN_PASSWORD" >> $GITHUB_ENV

      - name: create pull request
        # https://github.com/peter-evans/create-pull-request/releases/tag/v3.11.0 相当
        uses: peter-evans/create-pull-request@67df31e08a133c6a77008b89689677067fef169e
        with:
          # push 時に check-all-ci-result の対象にするために自前の TOKEN を使う
          token: '${{ secrets.DURIAN_BOT_GITHUB_TOKEN }}'
          commit-message: "feat: generate ansible vars for svn-user(${{ env.SVN_USERNAME }}) by GitHub Action"
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: create-pull-request/svn-user
          branch-suffix: random
          delete-branch: true
          title: '[自動作成] ${{ env.SVN_USERNAME }} の SVN ユーザ追加/更新'
          body: |
            この Pull Request は GitHub Actions によって自動作成されています。

            以下のユーザの SVN アカウント追加・更新が行われます。

            - アカウント名: ${{ env.SVN_USERNAME }}
            - グループ名: ${{ env.SVN_GROUPS }}

      # DM を送る
      - name: send DM to specific user(SLACK_MEMBER_ID)
        # https://github.com/slackapi/slack-github-action/tree/v1.18.0
        uses: slackapi/slack-github-action@16b6c78ee73689a627b65332b34e5d409c7299da
        with:
          channel-id: '${{ env.SLACK_MEMBER_ID }}'
          slack-message: |

            durian の SVN アカウントを発行します
            ※エンジニアが作業を完了するまで数時間かかる場合があります

            ---------------------------------------------------------------------
            アカウント : `${{ env.SVN_USERNAME }}`
            パスワード : `${{ env.SVN_PASSWORD }}`
            ---------------------------------------------------------------------

            接続方法は<https://mixigroup.docbase.io/posts/1773327|マニュアル>を参照してください。

            ※不明点や問い合わせは <https://xflag.slack.com/archives/G01DVTNGCJH|durian_dev チャネル>で `@durian-server` 宛にご連絡ください。

        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}

      # 失敗時はこちらのステップが実行される
      - name: Slack Notification on Failure
        # https://github.com/rtCamp/action-slack-notify/releases/tag/v2.2.0 相当
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7
        if: failure()
        env:
          SLACK_CHANNEL: durian_server
          SLACK_MESSAGE: ${{ env.SVN_USERNAME }} の SVN アカウント作成に失敗しました
          SLACK_COLOR: danger
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL_DURIAN_SERVER }}
