# svn user を削除する PR を作成します
name: delete-svn-user
on:
  workflow_dispatch:
    inputs:
      svn_username:
        description: SVNアカウント名を入力してください
        required: true
defaults:
  run:
    shell: bash
jobs:
  delete-svn-user:
    name: Create PR of delete svn user setting
    runs-on: ubuntu-20.04
    env:
      # 任意の文字列が入りうるフィールドは、Bashで直接使うとインジェクションの危険があるため、ENVに登録して使います
      # https://securitylab.github.com/research/github-actions-untrusted-input/#remediation
      SVN_USERNAME: ${{ github.event.inputs.svn_username }}
    steps:
      - name: checkout
      # https://github.com/actions/checkout/releases/tag/v2.4.0 相当
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: delete svn user variable
        run: |

          function prefail() { echo "$@" 1>&2; exit 1; }

          # validation check
          [[ "$SVN_USERNAME" =~ ^[A-Za-z\.-]+$ ]] || prefail "invalid SVN_USERNAME: $SVN_USERNAME"

          # delete ansible file
          ansible_file_path="ansible/host_vars/tools-svn/users/${SVN_USERNAME}.yaml"

          [[ -e "$ansible_file_path" ]] || prefail "no such file exists ($ansible_file_path)"
          git rm "$ansible_file_path"

      - name: create pull request
        # https://github.com/peter-evans/create-pull-request/releases/tag/v3.11.0 相当
        uses: peter-evans/create-pull-request@67df31e08a133c6a77008b89689677067fef169e
        with:
          # push 時に check-all-ci-result の対象にするために自前の TOKEN を使う
          token: '${{ secrets.DURIAN_BOT_GITHUB_TOKEN }}'
          commit-message: "feat: delete ansible vars for svn-user(${{ env.SVN_USERNAME }}) by GitHub Action"
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: create-pull-request/delete-svn-user
          branch-suffix: random
          delete-branch: true
          title: '[自動作成] ${{ env.SVN_USERNAME }} の SVN ユーザ削除'
          body: |
            この Pull Request は GitHub Actions によって自動作成されています。

            以下のユーザの SVN アカウント削除が行われます。

            - アカウント名: ${{ env.SVN_USERNAME }}

      # 失敗時はこちらのステップが実行される
      - name: Slack Notification on Failure
        # https://github.com/rtCamp/action-slack-notify/releases/tag/v2.2.0 相当
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7
        if: failure()
        env:
          SLACK_CHANNEL: durian_server
          SLACK_MESSAGE: ${{ env.SVN_USERNAME }} の SVN アカウント削除に失敗しました
          SLACK_COLOR: danger
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL_DURIAN_SERVER }}
