# Pull Requestに、除外したいユーザー(durian-bot)以外のコメントが投稿されたときに、Slackに投稿します。
# ただし、コメントの先頭が `[post slack]` で始まっている場合は必ずSlackに投稿します。
# Slackへの投稿形式は https://xflag.slack.com/apps/A01BP7R4KNY-github のものをほぼそのまま利用しています。

name: github-comment-to-slack

on:
  issue_comment:
    types:
      - created
  pull_request_review_comment:
    types:
      - created

jobs:
  github-comment-to-slack:
    name: GitHub comment to slack
    if: ${{ github.event.sender.login != 'durian-bot' || startsWith(github.event.comment.body, '[post slack]') }}
    runs-on: ubuntu-latest
    steps:
      # https://github.com/lirlia/github-comment-notifier-to-slack/releases/tag/v1.0.0
      - uses: lirlia/github-comment-notifier-to-slack@70b03974b745653fc4cc220a18c99039ca908286
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_DURIAN_SERVER }}
