name: post-medium
on:
  workflow_dispatch:
    inputs:
      article_date:
        description: articles/xxxxx の xxxx を入力してください
        required: true

jobs:
  post-medium:
    name: post-medium
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/matsubara0507/mdium
    env:
      MEDIUM_TOKEN: ${{ secrets.MEDIUM_TOKEN }}
      PUBLICATION_ID: ${{ secrets.PUBLICATION_ID }}
      ARTICLE_DATE: ${{ github.event.input.article_date }}
    steps:
      # https://github.com/actions/checkout/releases/tag/v2.4.0 相当
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - name: post-article
        shell: bash
        run: |

          set -x
          opt=(
            --title=$(cat articles/${ARTICLE_DATE}/title)
            --gist="medium-snippet-"
            --org="$PUBLICATION_ID"
            --verbose
          )
          # https://github.com/matsubara0507/mdium
          mdium articles/${ARTICLE_DATE}/README.md ${opt[@]}
