name: post-medium
on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - 'articles/**/README.md'
env:
  MEDIUM_TOKEN: ${{ secrets.MEDIUM_TOKEN }}
  PUBLICATION_ID: ${{ secrets.PUBLICATION_ID }}
jobs:
  post-medium:
    if: github.event.pull_request.merged == true
    name: post-medium
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/matsubara0507/mdium
    steps:
      # https://github.com/actions/checkout/releases/tag/v2.4.0 相当
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - run: |
          apt update -y
          apt install -y git
          files=$(git diff --name-only origin/main origin/${GITHUB_HEAD_REF} | grep README.md)
          for filepath in "$files"
          do
            title=$(sed -re "s@articles/(.*)/README.md@\1@g" <<< $filepath)
            opt=(
              --title="$title"
              --gist="medium-snippet-"
              --org="$PUBLICATION_ID"
              --verbose
            )
            # https://github.com/matsubara0507/mdium
            mdium "$filepath" ${opt[@]}
          done
