name: post-medium
on:
  workflow_dispatch:
    inputs:
      article_path:
        description: articles/xxxxx 形式で入力してください
        required: true

jobs:
  post-medium:
    name: post-medium
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/matsubara0507/mdium
    env:
      MEDIUM_TOKEN: ${{ secrets.MEDIUM_TOKEN }}
      PUBLICATION_ID: ${{ secrets.PUBLICATION_ID }}
      ARTICLE_PATH: ${{ github.event.inputs.article_path }}
      GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
    steps:
      # https://github.com/actions/checkout/releases/tag/v2.4.0 相当
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - name: post-article
        shell: bash
        run: |

          set -x

          # image url を更新
          sed -i "s@images@https://raw.githubusercontent.com/lirlia/medium/main/articles/template/images@g" "${ARTICLE_PATH}/README.md"

          opts=(
            --title="\"$(cat ${ARTICLE_PATH}/title)\""
            --gist="medium-snippet-"
            --org="$PUBLICATION_ID"
            --verbose
          )
          # https://github.com/matsubara0507/mdium
          mdium "${ARTICLE_PATH}/README.md" ${opts[@]}
